Improvements-to-benchmarks
Uplink036/EchoShield pull request #36
Opened 2024-12-19 12:16 UTC by AdamMutzell

Added more attacks, and cleaned up some stuff

2024-12-20 09:01 UTC, Uplink036 commented on benchmark_attacks.py
> -def band_pass_attack(data, sr, low, high):
Why did we remove this function? Even if it isn't good, it could be still a comparison point.

2024-12-20 09:04 UTC, Uplink036 requested changes
I still don't like that we send the output of the notebooks up on Github, but I'll remove that  for you.

That being said, why did you remove an attack? It might also be good, if you are finding these attacks through paper or online research, that we also leave a source to them. Let me know what you think.

2024-12-22 09:10 UTC, AdamMutzell commented
Lyckas alltid glömma bort att ta bort output, my bad.

Angående attacken så har jag bara förbättrat den och kallat den för amplify_dolphin_attack istället. Dessa attacker jag implementerat än så länge är enkla attacker jag själv kan komma på. Det finns inte så många andra black-box attacker där ute som går bra att jämföra med vår, och de som finns är rätt så komplicerade. Jag har en förhoppning om att hinna implementera en sådan ändå, om det finns tid

2024-12-23 09:30 UTC, Uplink036 commented
Check, that's what I wanted to know. Merging.

2024-12-23 09:34 UTC, Uplink036 approved these changes
I am fine with the comments and changes that have happened.

2024-12-23 09:34 UTC, merged