Save-And-Retreive-Weights
Uplink036/EchoShield pull request #44
Opened 2024-12-28 15:19 UTC by AdamMutzell

This branch makes it possible to save and load model weights. It is not fully tested, but small tests indicate that it works fine. Since my computer is a bit slow with Whisper, it is hard to run longer training sessions.

It also adds the attacks to the benchmark comparisions. Again, seems to work fine. 

I've also played around with adding more layers to the network. Really hard to tell if it is helping, but it seems that it atleast helps in keeping the noise levels low.

Lastly, I've changed the reward function slighty. I've added a modifier to the transcription_similarity, such that it cares more about it. I noticed that even though the similarity went down, the reward did not change much. This should help that problem.

Training and testing split still not done. Will be done in another branch

2024-12-31 02:57 UTC, Uplink036 commented on models/ddpg.py
> +    action_out = layers.Dense(64, activation="relu")(
Why did this value change from the input parameter to a constant?

2024-12-31 02:58 UTC, Uplink036 commented on environment/mel_env.py
> +    def perform_attack(self, action, audio, sr=41_000):
Really like this, would be nice if we used it in the step function, though I would be okay if we did this another time.

2024-12-31 02:59 UTC, Uplink036 commented on environment/audio_env.py
> +        return Levenshtein.ratio(original, predicted)**alpha
Why did this change to a alpha and why is that alpha 1 when it was 2?

2024-12-31 03:05 UTC, Uplink036 requested changes
A mostly fine commit, however, I do have some questions and am therefore hesitant to merge right now. Some can be argued if they need to be answered now, however, three points make me not want to merge: 
- Why are binary files a part of this merge request 
- Why did the Levenstein change, Is it a good thing that we can change it on the fly and why is the default not the same? That changes previous behavior. 
-  Regarding the new layer changes, I like most of them. I can see some being removed, but it's worth a try and probably better than before. However, why are we no longer considering the actor input parameter?

2025-01-01 14:45 UTC, AdamMutzell commented on models/ddpg.py
> +    action_out = layers.Dense(64, activation="relu")(
That's just my bad, will fix

2025-01-01 14:47 UTC, AdamMutzell commented on environment/audio_env.py
> +        return Levenshtein.ratio(original, predicted)**alpha
The fact that it was 2 was just arbitrary before. Having it default to 1 makes much more sense, but I see your point. The reason I tried to explain in the request, but to iterate: the reward function did not care enough about transcription similarity. This should help it by setting alpha to a larger value, to say 4 or 5.

2025-01-02 14:02 UTC, Uplink036 approved these changes
We've discoursed, relevant changes have been made and I approve.

2025-01-02 14:02 UTC, merged